# This notebook is just for collecting data

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import quandl
import datetime as datetime
import yfinance as yf
from yahoofinancials import YahooFinancials
from pytrends import dailydata
from pytrends.request import TrendReq

In [12]:
#data from blockchain.com using qunadl API
quandl.ApiConfig.api_key = '-7D4_v-SXngEYdwmFnfR' # get the API key to get datasets from quandl bitfinex database
df_price = quandl.get('BCHAIN/MKPRU') #bitcoin daily closing price
df_USD_ex_volume = quandl.get('BCHAIN/TRVOU') # daily exchange trade volume in USD
df_dif = quandl.get('BCHAIN/DIFF') # daily measure of difficutly of mining a block 
df_hash = quandl.get('BCHAIN/HRATE') #daily measure of hashrate
df_trasact_volume = quandl.get('BCHAIN/ETRAV') #daily number of transactional volume
df_transact_perblock = quandl.get('BCHAIN/NTRBL') # daily number of average transactions per block
df_transaction_no = quandl.get('BCHAIN/TRFUS') #daily number of total transactions
df_market_capitalization = quandl.get('BCHAIN/MKTCP') #bitcoin market capitalization by day

In [ ]:
dfl = [df_price, df_USD_ex_volume, df_dif, df_hash, df_trasact_volume, df_transact_perblock, df_transaction_no, df_market_capitalization]
#concatenate the different dataframes with an outerjoin, NaN values will be initial so should be filled with 0
from functools import reduce
df = reduce(lambda  left,right: pd.merge(left,right,on=['Date'], how='outer'), dfl).fillna(0)
#Rename the columns
df.columns = ['BTC_Price_USD', 'Trade_Vol_USD', 'Difficulty', 'HashRate', 'Transaction_Vol', 'Transactions_per_block', 'Total_Transactions','Market_Capitalization_USD']

#drop todays date because some columns will be null and will affect our analysis
df.drop(datetime.date.today(),axis = 0)

In [67]:
#Now adding the tech stocks accounted in NASDAQ 100
df_NASDAQ= yf.download('^OEX', start='2009-01-02',end=datetime.date.today() - datetime.timedelta(days=1), 
                       progress=False) #NASDAQ-100 data for tech stocks
df_NASDAQ= df_NASDAQ.drop(['Open','High','Low','Adj Close','Volume'], 1)
df_NASDAQ = df_NASDAQ.rename(columns={'Close': 'NASDAQ-100',})
df_NASDAQ.head()

            NASDAQ-100
Date
2009-01-02  444.519989
2009-01-05  440.829987
2009-01-06  442.720001
2009-01-07  429.839996
2009-01-08  430.380005

In [70]:
#Now for S&P 500
df_SandP500= yf.download('^GSPC', start='2009-01-02',end=datetime.date.today() - datetime.timedelta(days=1), 
                       progress=False) # S&P 500 data
df_SandP500= df_SandP500.drop(['Open','High','Low','Adj Close','Volume'], 1)
df_SandP500 = df_SandP500.rename(columns={'Close': 'S&P 500',})
df_SandP500.tail()

                S&P 500
Date
2022-03-07  4201.089844
2022-03-08  4170.700195
2022-03-09  4277.879883
2022-03-10  4259.520020
2022-03-11  4204.310059

In [73]:
#Now accounting for gold and silver, using the philadelphia gold and silver index
df_gold= yf.download('^XAU', start='2009-01-02',end=datetime.date.today() - datetime.timedelta(days=1), 
                       progress=False) #XAU index
df_gold= df_gold.drop(['Open','High','Low','Adj Close','Volume'], 1)
df_gold = df_gold.rename(columns={'Close': 'Gold & Silver',})
df_gold.tail()

            Gold & Silver
Date
2022-03-07     157.649994
2022-03-08     159.080002
2022-03-09     157.539993
2022-03-10     160.630005
2022-03-11     158.720001

In [75]:
# Now accounting for brent Oil price
df_oil= yf.download('CL=F', start='2009-01-02',end=datetime.date.today() - datetime.timedelta(days=1), 
                       progress=False) #XAU index
df_oil= df_oil.drop(['Open','High','Low','Adj Close','Volume'], 1)
df_oil = df_oil.rename(columns={'Close': 'Oil',})
df_oil.tail()

                   Oil
Date
2022-03-07  119.400002
2022-03-08  123.699997
2022-03-09  108.699997
2022-03-10  106.019997
2022-03-11  109.330002

In [114]:
#Now to get google search index data
df_interest = dailydata.get_daily_data('bitcoin', 2009, 1, 2022, 3)

bitcoin:2009-01-01 2009-01-31
bitcoin:2009-02-01 2009-02-28
bitcoin:2009-03-01 2009-03-31
bitcoin:2009-04-01 2009-04-30
bitcoin:2009-05-01 2009-05-31
bitcoin:2009-06-01 2009-06-30
bitcoin:2009-07-01 2009-07-31
bitcoin:2009-08-01 2009-08-31
bitcoin:2009-09-01 2009-09-30
bitcoin:2009-10-01 2009-10-31
bitcoin:2009-11-01 2009-11-30
bitcoin:2009-12-01 2009-12-31
bitcoin:2010-01-01 2010-01-31
bitcoin:2010-02-01 2010-02-28
bitcoin:2010-03-01 2010-03-31
bitcoin:2010-04-01 2010-04-30
bitcoin:2010-05-01 2010-05-31
bitcoin:2010-06-01 2010-06-30
bitcoin:2010-07-01 2010-07-31
bitcoin:2010-08-01 2010-08-31
bitcoin:2010-09-01 2010-09-30
bitcoin:2010-10-01 2010-10-31
bitcoin:2010-11-01 2010-11-30
bitcoin:2010-12-01 2010-12-31
bitcoin:2011-01-01 2011-01-31
bitcoin:2011-02-01 2011-02-28
bitcoin:2011-03-01 2011-03-31
bitcoin:2011-04-01 2011-04-30
bitcoin:2011-05-01 2011-05-31
bitcoin:2011-06-01 2011-06-30
bitcoin:2011-07-01 2011-07-31
bitcoin:2011-08-01 2011-08-31
bitcoin:2011-09-01 2011-09-30
bitcoin:2011-10-01 2011-10-31
bitcoin:2011-11-01 2011-11-30
bitcoin:2011-12-01 2011-12-31
bitcoin:2012-01-01 2012-01-31
bitcoin:2012-02-01 2012-02-29
bitcoin:2012-03-01 2012-03-31
bitcoin:2012-04-01 2012-04-30
bitcoin:2012-05-01 2012-05-31
bitcoin:2012-06-01 2012-06-30
bitcoin:2012-07-01 2012-07-31
bitcoin:2012-08-01 2012-08-31
bitcoin:2012-09-01 2012-09-30
bitcoin:2012-10-01 2012-10-31
bitcoin:2012-11-01 2012-11-30
bitcoin:2012-12-01 2012-12-31
bitcoin:2013-01-01 2013-01-31
bitcoin:2013-02-01 2013-02-28
bitcoin:2013-03-01 2013-03-31
bitcoin:2013-04-01 2013-04-30
bitcoin:2013-05-01 2013-05-31
bitcoin:2013-06-01 2013-06-30
bitcoin:2013-07-01 2013-07-31
bitcoin:2013-08-01 2013-08-31
bitcoin:2013-09-01 2013-09-30
bitcoin:2013-10-01 2013-10-31
bitcoin:2013-11-01 2013-11-30
bitcoin:2013-12-01 2013-12-31
bitcoin:2014-01-01 2014-01-31
bitcoin:2014-02-01 2014-02-28
bitcoin:2014-03-01 2014-03-31
bitcoin:2014-04-01 2014-04-30
bitcoin:2014-05-01 2014-05-31
bitcoin:2014-06-01 2014-06-30
bitcoin:2014-07-01 2014-07-31
bitcoin:2014-08-01 2014-08-31
bitcoin:2014-09-01 2014-09-30
bitcoin:2014-10-01 2014-10-31
bitcoin:2014-11-01 2014-11-30
bitcoin:2014-12-01 2014-12-31
bitcoin:2015-01-01 2015-01-31
bitcoin:2015-02-01 2015-02-28
bitcoin:2015-03-01 2015-03-31
bitcoin:2015-04-01 2015-04-30
bitcoin:2015-05-01 2015-05-31
bitcoin:2015-06-01 2015-06-30
bitcoin:2015-07-01 2015-07-31
bitcoin:2015-08-01 2015-08-31
bitcoin:2015-09-01 2015-09-30
bitcoin:2015-10-01 2015-10-31
bitcoin:2015-11-01 2015-11-30
bitcoin:2015-12-01 2015-12-31
bitcoin:2016-01-01 2016-01-31
bitcoin:2016-02-01 2016-02-29
bitcoin:2016-03-01 2016-03-31
bitcoin:2016-04-01 2016-04-30
bitcoin:2016-05-01 2016-05-31
bitcoin:2016-06-01 2016-06-30
bitcoin:2016-07-01 2016-07-31
bitcoin:2016-08-01 2016-08-31
bitcoin:2016-09-01 2016-09-30
bitcoin:2016-10-01 2016-10-31
bitcoin:2016-11-01 2016-11-30
bitcoin:2016-12-01 2016-12-31
bitcoin:2017-01-01 2017-01-31
bitcoin:2017-02-01 2017-02-28
bitcoin:2017-03-01 2017-03-31
bitcoin:2017-04-01 2017-04-30
bitcoin:2017-05-01 2017-05-31
bitcoin:2017-06-01 2017-06-30
bitcoin:2017-07-01 2017-07-31
bitcoin:2017-08-01 2017-08-31
bitcoin:2017-09-01 2017-09-30
bitcoin:2017-10-01 2017-10-31
bitcoin:2017-11-01 2017-11-30
bitcoin:2017-12-01 2017-12-31
bitcoin:2018-01-01 2018-01-31
bitcoin:2018-02-01 2018-02-28
bitcoin:2018-03-01 2018-03-31
bitcoin:2018-04-01 2018-04-30
bitcoin:2018-05-01 2018-05-31
bitcoin:2018-06-01 2018-06-30
bitcoin:2018-07-01 2018-07-31
bitcoin:2018-08-01 2018-08-31
bitcoin:2018-09-01 2018-09-30
bitcoin:2018-10-01 2018-10-31
bitcoin:2018-11-01 2018-11-30
bitcoin:2018-12-01 2018-12-31
bitcoin:2019-01-01 2019-01-31
bitcoin:2019-02-01 2019-02-28
bitcoin:2019-03-01 2019-03-31
bitcoin:2019-04-01 2019-04-30
bitcoin:2019-05-01 2019-05-31
bitcoin:2019-06-01 2019-06-30
bitcoin:2019-07-01 2019-07-31
bitcoin:2019-08-01 2019-08-31
bitcoin:2019-09-01 2019-09-30
bitcoin:2019-10-01 2019-10-31
bitcoin:2019-11-01 2019-11-30
bitcoin:2019-12-01 2019-12-31
bitcoin:2020-01-01 2020-01-31
bitcoin:2020-02-01 2020-02-29
bitcoin:2020-03-01 2020-03-31
bitcoin:2020-04-01 2020-04-30
bitcoin:2020-05-01 2020-05-31
bitcoin:2020-06-01 2020-06-30
bitcoin:2020-07-01 2020-07-31
bitcoin:2020-08-01 2020-08-31
bitcoin:2020-09-01 2020-09-30
bitcoin:2020-10-01 2020-10-31
bitcoin:2020-11-01 2020-11-30
bitcoin:2020-12-01 2020-12-31
bitcoin:2021-01-01 2021-01-31
bitcoin:2021-02-01 2021-02-28
bitcoin:2021-03-01 2021-03-31
bitcoin:2021-04-01 2021-04-30
bitcoin:2021-05-01 2021-05-31
bitcoin:2021-06-01 2021-06-30
bitcoin:2021-07-01 2021-07-31
bitcoin:2021-08-01 2021-08-31
bitcoin:2021-09-01 2021-09-30
bitcoin:2021-10-01 2021-10-31
bitcoin:2021-11-01 2021-11-30
bitcoin:2021-12-01 2021-12-31
bitcoin:2022-01-01 2022-01-31
bitcoin:2022-02-01 2022-02-28
bitcoin:2022-03-01 2022-03-31

In [126]:
df_interest = df_interest.drop(['bitcoin_unscaled','bitcoin_monthly','isPartial','scale'], 1)

In [148]:
df_interest = df_interest.rename(columns={'bitcoin': 'Interest_Index'})
df_interest.index.names = ['Date']
df_interest

            Interest_Index
Date
2009-11-01            0.00
2009-11-02            0.00
2009-11-03            0.00
2009-11-04            0.00
2009-11-05            0.00
...                    ...
2022-03-09           20.46
2022-03-10           18.92
2022-03-11           16.72
2022-03-12           14.08
2022-03-13            0.00

[4485 rows x 1 columns]

In [149]:
# fill forward and backward to fill missing data of stock indexes on weekends 
dfl2 = [df, df_NASDAQ, df_SandP500, df_gold, df_oil, df_interest] 
df_final = reduce(lambda  left,right: pd.merge(left,right,on=['Date'], how='outer'), dfl2).fillna(method ='bfill').fillna(method='ffill')
df_final.tail()

,BTC_Price_USD,Trade_Vol_USD,Difficulty,HashRate,Transaction_Vol,Transactions_per_block,Total_Transactions,Market_Capitalization_USD,NASDAQ-100,S&P 500,Gold & Silver,Oil,Interest_Index
Date,,,,,,,,,,,,,
2022-03-09,38753.10,2.790929e+08,2.755033e+13,1.889958e+08,150181.876330,1976.847826,469664.532772,7.975872e+11,1960.930054,4277.879883,157.539993,108.699997,20.46
2022-03-10,41956.53,4.096770e+08,2.755033e+13,1.985825e+08,122390.433409,1803.813793,462278.059192,7.522241e+11,1951.520020,4259.520020,160.630005,106.019997,18.92
2022-03-11,39437.89,3.600285e+08,2.755033e+13,1.889958e+08,134710.864322,1828.862319,434537.675717,7.375494e+11,1925.349976,4204.310059,158.720001,109.330002,16.72
2022-03-12,38741.04,2.679113e+08,2.755033e+13,2.136474e+08,36313.202224,1443.256410,308297.983710,7.419112e+11,1925.349976,4204.310059,158.720001,109.330002,14.08
2022-03-13,38809.18,1.162607e+08,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,1925.349976,4204.310059,158.720001,109.330002,0.00

In [150]:
df_final.drop(pd.Timestamp('2022-03-13')).tail()

,BTC_Price_USD,Trade_Vol_USD,Difficulty,HashRate,Transaction_Vol,Transactions_per_block,Total_Transactions,Market_Capitalization_USD,NASDAQ-100,S&P 500,Gold & Silver,Oil,Interest_Index
Date,,,,,,,,,,,,,
2022-03-08,38032.50,2.969851e+08,2.755033e+13,2.026911e+08,101263.905069,1728.182432,409089.188215,7.317727e+11,1908.599976,4170.700195,159.080002,123.699997,17.38
2022-03-09,38753.10,2.790929e+08,2.755033e+13,1.889958e+08,150181.876330,1976.847826,469664.532772,7.975872e+11,1960.930054,4277.879883,157.539993,108.699997,20.46
2022-03-10,41956.53,4.096770e+08,2.755033e+13,1.985825e+08,122390.433409,1803.813793,462278.059192,7.522241e+11,1951.520020,4259.520020,160.630005,106.019997,18.92
2022-03-11,39437.89,3.600285e+08,2.755033e+13,1.889958e+08,134710.864322,1828.862319,434537.675717,7.375494e+11,1925.349976,4204.310059,158.720001,109.330002,16.72
2022-03-12,38741.04,2.679113e+08,2.755033e+13,2.136474e+08,36313.202224,1443.256410,308297.983710,7.419112e+11,1925.349976,4204.310059,158.720001,109.330002,14.08

In [151]:
df_final.to_pickle('/Users/harrisasadb/Desktop/jupyter notebooks/crypto regression/Bitcoindata.pk1')

In [153]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4819 entries, 2009-01-02 to 2022-03-13
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   BTC_Price_USD              4819 non-null   float64
 1   Trade_Vol_USD              4819 non-null   float64
 2   Difficulty                 4819 non-null   float64
 3   HashRate                   4819 non-null   float64
 4   Transaction_Vol            4819 non-null   float64
 5   Transactions_per_block     4819 non-null   float64
 6   Total_Transactions         4819 non-null   float64
 7   Market_Capitalization_USD  4819 non-null   float64
 8   NASDAQ-100                 4819 non-null   float64
 9   S&P 500                    4819 non-null   float64
 10  Gold & Silver              4819 non-null   float64
 11  Oil                        4819 non-null   float64
 12  Interest_Index             4819 non-null   float64
dtypes: float64(13)
memory usage: 687.1 KB

### So far we have scraped data from blockchain.com, yahoo finance, and google trends. The only data remaining is the is the twitter sentiment analysis by date starting from 2009. we will need the tweepy library to do that and a full sentiment analysis need to measured for this whole time frame.

### This time intensive task will be done in parallel to doing our analysis with the above pickled dataset, but lets do some exploratory data analysis on this dataset and find out "what variables are most significant in affecting the  bitcoin price